### ISSUE TITLE
newline at end of fastq file results in NullPointerException

### ISSUE THREAD

**Issue by moritzschaefer** [KechrisLab/miR-MaGiC#2]
some fastq files have a newline at the end of the file. this makes your program crash. This is easily fixed and might save future users a considerable amount of time. 

log:

> Writing matches for reads in ../../sra_data.fastq to ../../mirnaout/kmer.sra_data.bam...
> Finished 1000000 reads
> Finished 2000000 reads
> Finished 3000000 reads
> Finished 4000000 reads
> Exception thrown while reading fastq file
> Exception in thread "main" java.lang.NullPointerException
>         at mirmagic.PerfectKmerSearch.samRecordFirstKmerMatchEachTarget(PerfectKmerSearch.java:271)
>         at mirmagic.PerfectKmerSearch.writeFirstKmerMatchEachTarget(PerfectKmerSearch.java:320)
>         at mirmagic.PerfectKmerSearch.main(PerfectKmerSearch.java:713)
> [Fri Dec 14 17:49:51 2018]
> Error in rule kmer_match_to_reference:
>     jobid: 4
>     output: ../../mirnaout/kmer.sra_data.bam
> 
> RuleException:
> CalledProcessError in line 81 of /home/moritz/Downloads/miR-MaGiC/pipeline/Snakefile:
> Command ' set -euo pipefail;  java -jar ../pipeline//PerfectKmerSearch.jar -b ../../mirnaout/kmer.sra_data.bam -fa ../../mature_edited.fa -fq ../../sra_data.fastq -k 20 ' returned non-zero exit status 1.
>   File "/home/moritz/Downloads/miR-MaGiC/pipeline/Snakefile", line 81, in __rule_kmer_match_to_reference
>   File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
> Removing output files of failed job kmer_match_to_reference since they might be corrupted:
> ../../mirnaout/kmer.sra_data.bam
> Shutting down, this might take some time.
> Exiting because a job execution failed. Look above for error message
> Complete log: /home/moritz/Downloads/miR-MaGiC/pipeline/.snakemake/log/2018-12-14T174542.175074.snakemake.log

**Comment by pamelarussell** [comment]
Thanks, will fix!

**Comment by moritzschaefer** [comment]
Thanks for your support and fast response

**Comment by pamelarussell** [comment]
Added helpful error message for this case
