### ISSUE TITLE
CombineCountsByGroup fails when mapped sequence is not available in reference 

### ISSUE THREAD

**Issue by moritzschaefer** [KechrisLab/miR-MaGiC#3]
> [Fri Dec 14 17:59:41 2018]
> rule collapse_counts_by_families:
>     input: ../../mirnaout/kmer.sra_data.sorted.bam, ../../mirnaout/kmer.sra_data.sorted.bai, ../resources/group_tables/miRBase_v21_group_by_core_ID_Mus_musculus.txt
>     output: ../../mirnaout/final_counts.sra_data.txt
>     jobid: 1
> 
> Job counts:
>         count   jobs
>         1       collapse_counts_by_families
>         1
> 
> Combining counts by group...
> Bam file:       ../../mirnaout/kmer.sra_data.sorted.bam
> Reference fasta file    ../../mature_edited.fa
> Group table:    ../resources/group_tables/miRBase_v21_group_by_core_ID_Mus_musculus.txt
> Plus strand mappings only:      true
> Reading sequences from fasta file ../../mature_edited.fa...
> Got 48884 sequences.
> Exception in thread "main" java.lang.NullPointerException
>         at mirmagic.CombineCountsByGroup.getMappedRecordNames(CombineCountsByGroup.java:83)
>         at mirmagic.CombineCountsByGroup.combinedCount(CombineCountsByGroup.java:97)
>         at mirmagic.CombineCountsByGroup.combinedCount(CombineCountsByGroup.java:103)
>         at mirmagic.CombineCountsByGroup.writeCombinedCounts(CombineCountsByGroup.java:110)
>         at mirmagic.CombineCountsByGroup.main(CombineCountsByGroup.java:129)

This is the code line in question (line 83 in CombineCountsByGroup): 

>		SAMRecordIterator iter = reader.query(refName, 0, refLen.get(refName).intValue(), false);

It seems that refName was not found in the reference fasta file (mature_edited.fa in my case. I substituted all spaces with underscores btw.), however I don't have the time to go deeper into the logic of the file atm.

both the mirna_gp and mirna both have the same sets of mirna names. It would be nice to have a proper error output in the case of a missing refName (so one could investigate which exact entry makes problems).

**Comment by moritzschaefer** [comment]
My bad! the reference fasta has of course to match the mirna_gp file

**Comment by moritzschaefer** [comment]
I rechecked: In fact there was a mismatch by ~50 miRNAs between the "Reference fasta file" and the "Group table". After making sure there was now overlap it ran through. I filed a PR which updates the musmusculus resource (2 mirnas were deprecated and 50 were missing from the current mirbase db) and adds a reference fasta file based on mirbase.

**Comment by pamelarussell** [comment]
PR merged. Thanks again!
